# ---------- Application Configurations ----------

# ------- Application Variables -------
$terminal = kitty
$fileManager = thunar
$menu = ~/.local/bin/rofi-toggle
$windowMenu = ~/.local/bin/rofi-toggle window


# ------- Terminal Env -------
env = TERMINAL,kitty
env = XDG_TERMINAL_EMULATOR,kitty
