source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/settings/primary-ppi.conf
$font = CaskaydiaCove NF SemiBold

general {
    hide_cursor = false
    grace = 0
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = $HOME/.config/hypr/settings/current_wallpaper
    blur_passes = 3
    blur_size = 5
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    noise = 0.0
}

input-field {
    monitor =
    size = $INPUT_W, $INPUT_H
    outline_thickness = $INPUT_OUTLINE
    inner_color = rgba(0, 0, 0, 0.3)

    outer_color = $primary $tertiary 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = $primary
    fade_on_empty = false

    font_family = $font
    placeholder_text = Enter Password...
    fail_text = $PAMFAIL

    position = $INPUT_X, $INPUT_Y
    halign = center
    valign = bottom
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = $TIME_FONT
    font_family = $font

    position = $TIME_X, $TIME_Y
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = $DATE_FONT
    font_family = $font

    position = $DATE_X, $DATE_Y
    halign = center
    valign = center
}
