# ---------- Window/Layer Rule Configurations ----------

# ------- Tags -------

# ----- Popups -----
windowrule = tag +popups, match:initial_title ^(Open File)$
windowrule = tag +popups, match:title ^(Choose Files)$
windowrule = tag +popups, match:title ^(Save As)$
windowrule = tag +popups, match:title ^(Confirm to replace files)$
windowrule = tag +popups, match:title ^(File Operation Progress)$
windowrule = tag +popups, match:class ^([Xx]dg-desktop-portal-gtk)$
windowrule = tag +popups, match:title ^(Open)$
windowrule = tag +popups, match:title ^(Authentication Required)$
windowrule = tag +popups, match:title ^(Add Folder to Workspace)$
windowrule = tag +popups, match:title ^(File Upload)(.*)$
windowrule = tag +popups, match:title ^(Choose wallpaper)(.*)$
windowrule = tag +popups, match:title ^(Library)(.*)$
windowrule = tag +popups, match:class ^(.*dialog.*)$
windowrule = tag +popups, match:title ^(.*dialog.*)$
windowrule = tag +popups, match:initial_title ^(Steam Settings)$
windowrule = tag +popups, match:class ^(steam)$


# ----- Utilities -----
windowrule = tag +utils, size (monitor_w*0.45), match:class ^(org.kde.dolphin)$
windowrule = tag +utils, size (monitor_w*0.55), match:class ^(org.pulseaudio.pavucontrol)$
windowrule = tag +utils, size (monitor_w*0.55), match:class ^(nwg-look)$
windowrule = tag +utils, match:class ^(cava)$
windowrule = tag +utils, match:class ^(cbonsai)$



# ----- Picture-in-Picture -----
windowrule = tag +picture-in-picture, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$

windowrule = float on, keep_aspect_ratio on, move ((monitor_w*0.73)) ((monitor_h*0.72)), size (monitor_w*0.25), pin on, match:tag picture-in-picture


# ----- Rules -----
windowrule = float on, match:tag popups
windowrule = float on, match:tag utils
windowrule = tile on, match:title ^(Steam)$


# ------- Window/Layer Effects -------

# ----- Utilities -----


# ----- Tooltip Focus -----
windowrule = no_focus on, match:title ^(?i)(tooltip|popup|popupmenu|context|notification|completion|code completion|intention|hint)$
windowrule = no_focus on, match:class ^(.*jetbrains.*)$, match:title ^(win[0-9]+)$


# ----- Blur -----
layerrule = blur on, ignore_alpha 0, match:namespace rofi
layerrule = blur on, ignore_alpha 0, match:namespace waybar



# ------- Scroll/Trackpad Settings -------
windowrule = scroll_touchpad 1, match:class ^(kitty)$
windowrule = scroll_touchpad 0.25, scroll_mouse 3, match:initial_class ^(jetbrains-fleet)$
